### ISSUE TITLE
This won't compile

### ISSUE THREAD

**Issue by jshou** [raboof/sfarkxtc#3]
It fails on line 37:

```
#include "sfArkLib.h"
```

which isn't included in the repo.

**Comment by raboof** [comment]
Hi Joshua,

Thanks for your message. It's funny I didn't have this problem on Travis or on my machine, but indeed the import statement should be `#include <sfArkLib.h>` rather than `#include "sfArkLib.h"`. Thanks for the pointer, should be fixed now!

(you might still run into trouble if you haven't installed sfArkLib yet)

**Comment by QuaxEros** [comment]
Hello raboof,

Tried to "make" after putting sfArkLib.h (from sfArkLib) in the same directory. Still fails with "file not found" error.
 I should say i almost never "built" or worked with git before. Should this work or do i really need to install sfArkLib before or is the location of sfArkLib.h not correct? (you say in the readme "If you just want to convert an sfArk file to sf2, check out https://github.com/raboof/sfArkXTm" but then mention sfArkLib again as a prerequisite.)
Thanx for your work!
